services:
  mysql_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gymrat
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - /etc/localtime:/etc/localtime:ro
  phpmyadmin:
    depends_on:
      - mysql_db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 5000:80
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Colombo
  php-server:
    build: .
    ports:
      - 80:80
    volumes:
      - ../src:/var/www/html
    environment:
      TZ: Asia/Colombo
  
volumes:
  db_data:
